### ISSUE TITLE
Needs a version tag

### ISSUE THREAD

**Issue by jackfiszr** [skoshx/deno-open#2]
Hi,

I don't know if you are aware that if you don't add at least one tag (like e.g. v0.0.1) the module will soon be deleted from Deno's registry.

**Comment by skoshx** [comment]
> Hi,
> 
> 
> 
> I don't know if you are aware that if you don't add at least one tag (like e.g. v0.0.1) the module will soon be deleted from Deno's registry.

Hello, how would I go about doing that?

**Comment by jackfiszr** [comment]
Go to your project directory and run:

    git tag v0.0.1
    git push origin v0.0.1
