### ISSUE TITLE
Hide console output

### ISSUE THREAD

**Issue by martin-braun** [skoshx/deno-open#7]
I'm using deno-open in scripts and I don't like the output that is generated in the index.ts: 

```ts
console.log("Running command");
console.log(command, ...cliArguments);
```

Can this lib provide a flag for silent mode or can this be removed altogether?

**Comment by skoshx** [comment]
@martin-braun Hello, thanks for opening this issue... Those logs are not supposed to be there and are now removed in `open@v0.0.5`.

```typescript
import { open } from 'https://deno.land/x/open@v0.0.5/index.ts'
```
