### ISSUE TITLE
URL with `&` in query string only passes the first arg

### ISSUE THREAD

**Issue by laurence-myers** [skoshx/deno-open#9]
## Test case

On Windows 10 via PowerShell.

```typescript
await open('https://www.google.com/search?sclient=gws-wiz&q=deno_open', { url: true })
```

## Expected

Opens browser with URL `https://www.google.com/search?sclient=gws-wiz&q=deno_open`

## Actual

Opens browser with URL `https://www.google.com/search?sclient=gws-wiz`

**Comment by skoshx** [comment]
Thanks for opening this issue!

I'm unable to reproduce this on macOS, so it's difficult to help with any kind of fix for now!

**Comment by laurence-myers** [comment]
Looks like, in Windows, you just need to wrap the `&` char in quote marks, e.g. `https://www.google.com/search?sclient=gws-wiz"&"q=deno_open`. (Wrapping the whole string does not work.)

I've tested this in both Command Prompt and PowerShell.

```cmd
C:\Users\...>start http://www.google.com/search?client=firefox-b-d&q=deno+open
'q' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\...>start http://www.google.com/search?client=firefox-b-d"&"q=deno+open
```

```PowerShell
PS C:\Users\...> start http://www.google.com/search?client=firefox-b-d&q=deno+open
At line:1 char:54
+ start http://www.google.com/search?client=firefox-b-d&q=deno+open
+                                                      ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

PS C:\Users\...> start http://www.google.com/search?client=firefox-b-d"&"q=deno+open
```

**Comment by skoshx** [comment]
Haha, another interesting quirk of Windows it seems :D But thank you for taking your time to investigate this! I will add a note to the README!
